# Site settings
title: "PhoenixCon"
email: dev@phoenix.apache.org
url: https://phoenix.apache.org/phoenixcon-2018/
description: "PhoenixCon 2018"
keywords: "phoenixcon apache phoenix"
skills: "June 18th, 2018 - Joseph McEnery Convention Center, San Jose, CA"
logo: phoenix.png
pmc: Phoenix
cfp: https://easychair.org/conferences/?conf=pc18

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: a0a0a0 #194,17,26 : 187, 15,20
  links: e82727
  primary-rgb: "194,17,26"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Apache Software Foundation

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
baseurl: /phoenixcon-2018
